name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install rich requests

    - name: Run Python syntax check
      run: |
        python -m py_compile IP_Reputation/*.py main.py

    - name: (Optional) Run unit tests
      run: |
        echo "No tests found. Add test scripts in the Test/ folder."
        # Ví dụ nếu có unittest: python -m unittest discover -s Test

    - name: (Optional) Lint with flake8
      run: |
        pip install flake8
        flake8 IP_Reputation main.py

